#!/bin/bash
echo "Mounting NFS to /shared"
if [ ! -f /etc/systemd/system/shared.mount ]
then
	cat << EOF > /etc/systemd/system/shared.mount
[Unit]
Description=Mount NFS to /shared
Before=dcos-mesos-slave.service

[Install]
RequiredBy=dcos-mesos-slave.service

[Mount]
What=${NFS_WHAT}
Where=/shared
Type=${NFS_TYPE:-nfs4}
Options=${NFS_OPTIONS:-nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,fsc}
EOF
systemctl daemon-reload
fi

rpm -q cachefilesd > /dev/null || yum -y install cachefilesd
mkdir -p /dcos/volume0/fscache
sed -i'' \
  -e 's#^dir .*#dir /dcos/volume0/fscache#' \
  -e 's/^brun .*/brun 30%/'   \
  -e 's/^bcull .*/bcull 20%/' \
  -e 's/^bstop .*/bstop 15%/' \
  /etc/cachefilesd.conf
systemctl is-enabled cachefilesd.service > /dev/null || systemctl enable cachefilesd.service
systemctl restart cachefilesd.service

systemctl is-enabled shared.mount > /dev/null || systemctl enable shared.mount
systemctl is-active shared.mount > /dev/null || systemctl start shared.mount

while :
do
	echo "Mount finished - kill this job!"
	sleep 300
done
