#!/bin/bash

if [ -z "${NFS_WHAT-}" ]; then
  echo "NFS_WHAT environment variable is undefined"
  exit 1
fi

echo "Copying NFS mount script to host filesystem"
cp /sbin/mount-nfs /host/tmp/mount-nfs

echo "Chrooting into the host filesystem"
chroot /host /tmp/mount-nfs
