#!/bin/bash

if [ -z "${NFS_WHAT-}" ]; then
  echo "NFS_WHAT environment variable is undefined"
  exit 1
fi

echo "Copying NFS mount script to host filesystem"
cp -a /scripts /host/tmp/

echo "Chrooting into the host filesystem"
chroot /host $*
